alert(`Vamos a calcular la velocidad de un proyecti...`)
let num1 = Number(prompt(`Cual es la distancia que recorre en kilometros el proyectil? `))
let num2 = Number(prompt(`En cuantos minutos los recorre? `))
vel = (num1*1000)/(num2*60)
console.log(`Teniendo esto claro tenemos que nuestro resultado en m/s seria= ${vel}`)